name: jwt-djrest

secrets:
  infisical_token:
    file: ./infisical_token.txt
  .infisical.json:
    file: ./.infisical.json

services:
  jwt-djrest-backend:
    container_name: jwt-djrest-backend
    build: ./backend
    image: jwt-djrest-backend:Python-3.12-slim-D
    ports:
      - "8001:8000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c 
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./backend:/app
    depends_on:
      jwt-djrest-redis:
        condition: service_healthy
    networks:
      - web-app-network

  jwt-djrest-frontend:
    container_name: jwt-djrest-frontend
    build: ./frontend
    image: jwt-djrest-frontend:Node-20-alpine-D
    ports:
      - "3001:3000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: sh -c
    command: ["chmod +x /app/run.sh && /app/run.sh"]
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    extra_hosts:
      - "jwt-djrest.dev:host-gateway"
    networks:
      - web-app-network

  jwt-djrest-redis:
    build: ./redis
    container_name: jwt-djrest-redis
    image: jwt-djrest-redis:Redis-7.4.2-alpine-D
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - web-app-network

volumes:
  frontend_node_modules:
  redis-data:

networks:
  web-app-network:
    external: true