name: jwt-djrest

secrets:
  infisical_token:
    file: ./infisical_token.txt
  .infisical.json:
    file: ./.infisical.json

services:
  jwt-djrest-backend:
    container_name: jwt-djrest-backend
    build: ./backend
    image: jwt-djrest-backend:Python-3.12-alpine-P
    restart: unless-stopped
    ports:
      - "8001:8000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: /app/run.sh
    volumes:
      - backend-static:/app/static
    depends_on:
      jwt-djrest-redis:
        condition: service_healthy
    networks:
      - web-app-network
    cpus: '1'
    mem_limit: 1g

  jwt-djrest-frontend:
    container_name: jwt-djrest-frontend
    build: ./frontend
    image: jwt-djrest-frontend:Node-20-alpine-P
    restart: unless-stopped
    ports:
      - "3001:3000"
    secrets:
      - infisical_token
      - .infisical.json
    entrypoint: /app/run.sh
    extra_hosts:
      - "jwt-djrest.dev:host-gateway"
    networks:
      - web-app-network
    cpus: '0.5'
    mem_limit: 512m

  jwt-djrest-redis:
    build: ./redis
    container_name: jwt-djrest-redis
    image: jwt-djrest-redis:Redis-7.4.2-alpine-P
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - web-app-network
    cpus: '0.3'
    mem_limit: 256m

volumes:
  backend-static:
    driver: local
  redis-data:
    driver: local

networks:
  web-app-network:
    external: true