import type { Metadata } from "next";
import Navbar from "@/components/navbar/Navbar";
import { getSessionCookie } from "@/libs/cookie";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "JWT Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSessionCookie();
  const isLoggedIn = !!session;

  return (
    <html lang="en">
      <body className="bg-gray-200 min-h-screen">
        <Navbar isLoggedIn={isLoggedIn} />
        {children}
      </body>
    </html>
  );
}

