# Generated by Django 5.1.5 on 2025-01-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_db', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
